name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Debugging step to verify the current directory and list files
    - name: Print current directory and list files
      run: |
        pwd
        ls -R

    # Build the project by specifying the correct relative path to the .csproj file
   # - name: Build & Install
   #   run: dotnet build TestProject/TestProject.csproj

    # Ensure browsers are installed by running the PowerShell script
   # - name: Ensure browsers are installed
   #   shell: pwsh  # Use PowerShell shell
   #   run: |
   #     pwsh pw-swag-app/bin/Debug/net8.0/playwright.ps1 install --with-deps

    # Run your tests by specifying the relative path to the test project
    - name: Run your tests
      run: dotnet test TestProject/TestProject.csproj
